config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "courses#index", :as => :authenticated_root
  end
  unauthenticated do
    root to: redirect("/users/sign_in")
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations", :confirmations => "confirmations",
    :passwords => "passwords" }
  get '/privacy', to: 'application#privacy'
  resources :templates do
    get 'remove'
    get 'fill_form'
  end

  resources :courses do
    get 'remove'
    resources :assignments, shallow: true do
      get 'remove'
      resources :problems, shallow: true do
        get 'remove'
        resources :test_cases, shallow: true do
          get 'toggle_flag'
          get 'remove'
          get 'edit'
          get 'cancel'
        end
      end
    end
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	self.primary_key = 'id'
	# Sorting
	default_scope { order 'due ASC' }
	# Relationships
	has_many :problems
	belongs_to :course
	belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
	belongs_to :remover, :class_name => 'User', :foreign_key => 'remover_id'
	# Validation
	validates :name, presence: true
	validates :due, presence: true
	validates :creator, presence: true
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
	#-----------------------DEFAULT RESTFUL ACTIONS-------------------------------
	def index
		raise "You must be logged in to access this." unless current_user
		@assignments = @course.assignments.all
	end

	def create
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		@course = Course.find(params[:course_id])
		@assignment = @course.assignments.build(assignment_params)
		@assignment.course = @course
		@assignment.creator = current_user
		save_created_object @assignment
	end

	def show
		raise "You must be logged in to access this." unless current_user
		@assignment = Assignment.find(params[:id])
		@course = @assignment.course
		@problem = Problem.new
	end
	#---------------------OTHER RESTFUL ACTIONS-----------------------------------
	def remove
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		@assignment = Assignment.find(params[:assignment_id])
		@course = @assignment.course
		remove_object @assignment
	end
	#---------------------EXTERNALIZED FUNCTIONS----------------------------------
	def assignment_params
    params.require(:assignment).permit(:name, :due)
	end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignment_form.html.erb
<%= form_for [course, assignment], :html => {class: 'form-inline row'}, validate: true, remote: true do |form| %>
  <div class="form-group col-md-4">
	     <%= form.text_field :name, class: "form-control input-lg", placeholder: "Name" %>
	</div>
	<div class="form-group col-md-4">
	     <%= form.date_field :due, class: "form-control input-lg", value: Date.today %>
	</div>
	<div class="form-group col-md-4">
	     <%= form.submit "New Assignment", class: "btn btn-white btn-lg pull-right" %>
	</div>
<% end %>

app/views/assignments/_assignment_list.html.erb
<% course.assignments.each do |a| %>
	<% if !a.removed %>
		<div class="row">
			<div class="col-md-4">
				<h3><%= a.name %></h3>
			</div>

			<div class="col-md-4">
				<h3><%= a.due %></h3>
			</div>

			<div class="col-md-4">
				<% if current_user.admin %>
					<%= button_to "View", assignment_path(a), class: "btn btn-success pull-left btn-lg panel-btn btn-std", style: "margin-top: 10px", :method => :get %>
					<%= button_to "Delete", assignment_remove_path(a), class: "btn btn-danger pull-left btn-lg btn-std", style: "margin-top: 10px", remote: true, :method => :get %>
				<% else %>
					<%= button_to "View", assignment_path(a), class: "btn btn-success pull-right btn-lg btn-std", style: "margin-top: 10px", :method => :get %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/assignments/create.js.erb
$("#assignments_panel").html('<%= escape_javascript( render :partial => "assignment_list", :locals => {course: @course} )%>');
$("#assignment_name").val('');
$("#flash-container").html('<%= escape_javascript(render :partial => "shared/flash_box") %>');
<% flash.discard %>

app/views/assignments/remove.js.erb
$("#assignments_panel").html('<%= escape_javascript( render :partial => "assignments/assignment_list", :locals => { course: @course } ) %>');
$("#flash-container").html('<%= escape_javascript(render :partial => "shared/flash_box") %>');
<% flash.discard %>

app/views/assignments/show.html.erb
<% content_for :navbar do %>
	<li> <%= link_to  @course.code, @course, class: "nav-text" %> </li>
	<li> <a> > </a> </li>
	<li> <%= link_to @assignment.name, @assignment %> </li>
<% end %>

<div class="page-header">
	<h1><%= @assignment.name %></h1>
</div>

<div class="panel">
	<div class="panel-heading panel-heading-style">
		<% if current_user &&  current_user.admin %>
			<%= button_to "New Problem", new_assignment_problem_path(@assignment), class: "btn btn-lg btn-white", :method => :get %>
		<% end %>
	</div>

	<div class="panel-body panel-body-style" id="problems_panel">
		<%= render partial: "problems/problem_list", :locals => { assignment: @assignment } %>
	</div>
</div>