config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "courses#index", :as => :authenticated_root
  end
  unauthenticated do
    root to: redirect("/users/sign_in")
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations", :confirmations => "confirmations",
    :passwords => "passwords" }
  get '/privacy', to: 'application#privacy'
  resources :templates do
    get 'remove'
    get 'fill_form'
  end

  resources :courses do
    get 'remove'
    resources :assignments, shallow: true do
      get 'remove'
      resources :problems, shallow: true do
        get 'remove'
        resources :test_cases, shallow: true do
          get 'toggle_flag'
          get 'remove'
          get 'edit'
          get 'cancel'
        end
      end
    end
  end

end

app/views/templates/_templates_list.html.erb
<% templates.each do |t| %>
  <% if !t.removed %>
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <h3><%= t.name %></h3>
      </div>
      <div class="col-md-4">
        <% if current_user.admin %>
          <%= button_to "Edit", edit_template_path(t), class:"btn btn-info pull-left btn-lg panel-btn", :method => :get%>
          <%= button_to "Delete", template_remove_path(t), class:"btn btn-danger pull-left btn-lg panel-btn", :method => :get, remote: true %>
        <% else %>
          <%= button_to "View", template_path(t), class:"btn btn-success pull-right btn-lg", :method => :get %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/templates/edit.html.erb
<div class="page-header">
	<h2>Edit Template</h2>
</div>

<div class="panel">
	<div class="panel-body" id="problems_panel">
    <%= form_for [@template], validate: true do |form| %>
		<!-- Form at the heading -->
    <div class="col-md-10 col-md-offset-1">
        <%= form.text_field :name, class: "form-control input-lg", placeholder: "Template Name" %>
    </div>
		<!-- Instructions -->
		<div class="col-md-10 col-md-offset-1">
			<h3> <%= form.label :instructions,  "Instructions" %> </h3>
      <%= form.text_area :instructions, class: "form-control", placeholder: "Instructions Here",
			style: "width:100%; height:250px;" %>
    </div>
		<!-- Text area for code -->
    <div class="col-md-10 col-md-offset-1">
			<div class="row">
				<h3 style="display: inline-block;"> <%= form.label :source,  "Template Code" %> </h3>
				<div class="pull-right">
					<br>
					<%= form.select :mode, ::Template::MODES, {}, class: "form-control",
					onChange: "changeMode();" %>
				</div>
			</div>
			<div class="codemirror-pane">
      	<%= form.text_area :code, class: "form control", id: "codemirror" %>
			</div>
		</div>
		<!-- Submit button -->
    <div class="form-group text-center">
      <%= form.submit "Update Template", class: "btn btn-style btn-lg" %>
    </div>
    <% end %>
	</div>
</div>
<script>
	var codeMirror;
	var changeMode = function(){
		codeMirror.setOption("mode", $('#template_mode').val());
	}
	var ready = function(){
			var current = $('template_mode').val();
			codeMirror = CodeMirror.fromTextArea($('#codemirror')[0], {
				lineNumbers: true,
				mode: current ? current : "<%= ::Template::MODES[0] %>",
				height: "300px"
			});
	};
	$(document).ready(ready);
	$(document).on('page:load', ready);
</script>

app/views/templates/fill_form.js.erb
$('#instructions').val('<%= raw j @template.instructions %>');
$("#template_mode").val('<%= @template.mode %>');
codeMirror.doc.setValue('<%= raw j @template.code %>');
changeMode();

app/views/templates/index.html.erb
<div class="page-header" style="margin-top: 0px;">
	<h1>Templates</h1>
</div>

<div class="panel">
	<div class="panel-heading panel-heading-style">
		<%= button_to "New Template", new_template_path, class: "btn btn-lg btn-white", :method => :get %>
	</div>

	<div class="panel-body panel-body-style" id="templates_panel">
		<%= render partial: 'templates_list', :locals => { templates: @templates } %>
	</div>
</div>

app/views/templates/new.html.erb
<div class="page-header">
	<h2>New Template</h2>
</div>

<div class="panel">
	<div class="panel-body" id="problems_panel">
    <%= form_for [@template], validate: true do |form| %>
		<!-- Form at the heading -->
    <div class="col-md-10 col-md-offset-1">
        <%= form.text_field :name, class: "form-control input-lg", placeholder: "Template Name" %>
    </div>
		<!-- Instructions -->
		<div class="col-md-10 col-md-offset-1">
			<h3> <%= form.label :instructions,  "Instructions" %> </h3>
      <%= form.text_area :instructions, class: "form-control", placeholder: "Instructions Here",
			style: "width:100%; height:250px;" %>
    </div>
		<!-- Text area for code -->
    <div class="col-md-10 col-md-offset-1">
			<div class="row">
				<h3 style="display: inline-block;"> <%= form.label :source,  "Template Code" %> </h3>
				<div class="pull-right">
					<br>
					<%= form.select :mode, ::Template::MODES, {}, class: "form-control",
					onChange: "changeMode();" %>
				</div>
			</div>
			<div class="codemirror-pane">
      	<%= form.text_area :code, class: "form control", id: "codemirror" %>
			</div>
		</div>
		<!-- Submit button -->
    <div class="form-group text-center">
      <%= form.submit "Create Template", class: "btn btn-style btn-lg" %>
    </div>
    <% end %>
	</div>
</div>
<script>
	var codeMirror;
	var changeMode = function(){
		codeMirror.setOption("mode", $('#template_mode').val());
	};
	var ready = function(){
			var current = $('template_mode').val();
			codeMirror = CodeMirror.fromTextArea($('#codemirror')[0], {
				lineNumbers: true,
				mode: current ? current : "<%= ::Template::MODES[0] %>",
				height: "300px"
			});
	};
	$(document).ready(ready);
	$(document).on('page:load', ready);
</script>

app/views/templates/remove.js.erb
$("#templates_panel").html('<%= escape_javascript( render partial: "templates_list", :locals => { templates: @templates } ) %>');
$("#flash-container").html('<%= escape_javascript(render :partial => "shared/flash_box") %>');
<% flash.discard %>