config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "courses#index", :as => :authenticated_root
  end
  unauthenticated do
    root to: redirect("/users/sign_in")
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations", :confirmations => "confirmations",
    :passwords => "passwords" }
  get '/privacy', to: 'application#privacy'
  resources :templates do
    get 'remove'
    get 'fill_form'
  end

  resources :courses do
    get 'remove'
    resources :assignments, shallow: true do
      get 'remove'
      resources :problems, shallow: true do
        get 'remove'
        resources :test_cases, shallow: true do
          get 'toggle_flag'
          get 'remove'
          get 'edit'
          get 'cancel'
        end
      end
    end
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base
	self.primary_key = 'id'
	# Sorting
	default_scope { order 'number ASC' }
	# Relationships
	has_many :test_cases
	belongs_to :assignment
	belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
	belongs_to :remover, :class_name => 'User', :foreign_key => 'remover_id'
	# Validation
	validates :number, presence: true
	validates :creator, presence: true
	validates :source, presence:
	# Constant
	MODES = {"Python" => "text/x-python", "C++" => "text/x-c++src"}
	#------------------INSTANCE METHODS-------------------------------------------
	def initialize(attributes={}, options={})
    attr_with_defaults = {:source => PYTHON_PRINT_TEMPLATE,
			:instructions => INSTRUCTIONS_TEMPLATE_PYTHON}.merge(attributes)
    super(attr_with_defaults)
  end

	def generate_source
		test_cases = self.test_cases
		source = self.source
		generated_source = source.dup
		# Splits the strings from regexes
		error_prefix = "ERROR PARSING SOURCE:"
		# {{count}}
		generated_source.gsub! '{{count}}', self.test_cases.count.to_s
		# {{each}}
		split = generated_source.split(/{{each}}/)
		if split.count != 2
			return error_prefix + "{{each}} must be used exactly once"
		end
		before = split[0]
		after = split[1]
		# {{end}}
		split = after.split(/{{end}}/)
		if split.count != 2
			return error_prefix + "{{end}} must be used exactly once after {{each}}"
		end
		test_loop = split[0]
		after = split[1]
		# Starts building the code
		generated_source = before
		counter = 0
		self.test_cases.each do |test|
			if !test.removed
				input = test.input.dup
				output = test.output.dup
				input.gsub! /\r\n/, '\\n'
				output.gsub! /\r\n/, '\\n'
				test_string = test_loop.dup
				test_string.gsub! '{{index}}', counter.to_s
				test_string.gsub! '{{input}}', input
				test_string.gsub! '{{output}}', output
				generated_source += test_string
				counter += 1
			end
		end
		generated_source += after

		return generated_source
	end

	def update_source!
		source = generate_source
		self.update_column(:generated_source, source)
	end

end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
	#-----------------------DEFAULT RESTFUL ACTIONS-------------------------------
	def index
		raise "You must be logged in to access this." unless current_user
		@problem = Problem.find(params[:id])
	end

	def create
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		@assignment = Assignment.find(params[:assignment_id])
		@problem = @assignment.problems.new(problem_params)
		@problem.assignment = @assignment
		@problem.creator = current_user
	  @problem.generated_source = @problem.generate_source
		save_created_object @problem
	end

	def new
		raise "You must be logged in to access this." unless current_user
		@assignment = Assignment.find(params[:assignment_id])
		@course = @assignment.course
		@problem = Problem.new
		@templates = Template.all
	end

	def edit
		raise "You must be logged in to access this." unless current_user
		@problem = Problem.find(params[:id])
		@assignment = @problem.assignment
		@course = @assignment.course
	end

	def update
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		@problem = Problem.find(params[:id])

		updated = @problem.update_attributes(problem_params)
		if updated
			@problem.generated_source = @problem.generate_source
			save_object @problem
		else
			respond_to do |format|
				format.html  {
					render :text => "An error occured while saving".html_safe
				}
				format.json
			end
		end
	end

	def show
		raise "You must be logged in to access this." unless current_user
		@problem = Problem.find(params[:id])
		@assignment = @problem.assignment
		@course = @assignment.course
	end
	#---------------------OTHER RESTFUL ACTIONS-----------------------------------
	def remove
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		@problem = Problem.find(params[:problem_id])
		@assignment = @problem.assignment
		remove_object @problem
	end

	def get_template
		raise "Unauthorized Access! You must be an admin to do this." unless current_user.admin
		puts "----------------TEMPLATES ID=|" + params[:template_id] + "|-------------------"
		@template = Template.find(params[:template_id])
		respond_to do |format|
			if @template
				format.js
			end
		end
	end
	#---------------------EXTERNALIZED FUNCTIONS----------------------------------
	def problem_params
      params.require(:problem).permit(:number, :part, :source, :instructions)
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  def get_name
    "Problem " + @problem.number.to_s + (@problem.part ? "." + @problem.part.to_s : "")
  end
end

app/views/problems/_problem_list.html.erb
<% assignment.problems.each do |p| %>
	<% if !p.removed %>
		<div class="row">
			<div class="col-md-4 col-md-offset-2">
				<h3>Problem <%= p.number.to_s %><% if p.part %>.<%= p.part.to_s %><% end %></h3>
			</div>

			<div class="col-md-4">
				<% if current_user.admin %>
					<%= button_to "View", problem_path(p), class:"btn btn-success pull-left btn-lg", :method => :get %>
					<%= button_to "Edit", edit_problem_path(p), class:"btn btn-info pull-left btn-lg panel-btn", :method => :get%>
					<%= button_to "Delete", problem_remove_path(p), class:"btn btn-danger pull-left btn-lg panel-btn", :method => :get, remote: true %>
				<% else %>
					<%= button_to "View", problem_path(p), class:"btn btn-success pull-right btn-lg", :method => :get %>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/problems/_test_source.html.erb
<div class="panel" id="source">
  <div class="panel-heading panel-heading-style text-center">
    <h2>Test Source</h2>
  </div>
  <div class="panel-body">
    <textarea id="codemirror-read"><%= problem.generated_source %></textarea>
  </div>
</div>

app/views/problems/edit.html.erb
<% content_for :navbar do %>
	<li> <%= link_to @course.code, @course %> </li>
	<li> <a> > </a> </li>
	<li> <%= link_to @assignment.name, @assignment %> </li>
	<li> <a> > </a> </li>
  <li> <%= link_to get_name, @problem %> </li>
  <li> <a> > </a> </li>
	<li> <a>Edit</a> </li>
<% end %>

<div class="page-header">
	<h2>Edit Problem</h2>
</div>

<% if  current_user && current_user.admin %>
	<div class="panel panel-success">
		<div class="panel-body" id="problems_panel">
	    <%= form_for @problem, validate: true do |form| %>
				<!-- Heading at the top -->
		    <div class="row">
		      <div class="form-group col-md-4 col-md-offset-2">
		        <%= form.number_field :number, class: "form-control input-lg", placeholder: "Problem Num." %>
		      </div>
		      <div class="form-group col-md-4">
		        <%= form.number_field :part, class: "form-control input-lg", placeholder: "Part (Optional)" %>
		      </div>
		    </div>
				<!-- Instructions -->
				<div class="col-md-10 col-md-offset-1">
					<h3> <%= form.label :instructions,  "Instructions" %> </h3>
		      <%= form.text_area :instructions, class:"form-control", placeholder:"Instructions Here", style:"width:100%; height:250px;" %>
		    </div>
				<!-- Text area for code-->
		    <div class="col-md-10 col-md-offset-1">
					<h3> <%= form.label :source,  "Unit Testing Source Template" %> </h3>
					<h4>The format must remain the same as the default to automatically generate the unit test source code</h4>
		      <%= form.text_area :source, class:"form control", id: "codemirror", placeholder:"Source Here", style:"width:100%; height:250px;" %>
		    </div>
				<!-- Submit button -->
		    <div class="form-group text-center">
		      <%= form.submit "Save Changes", class: "btn btn-info btn-lg" %>
		    </div>
	    <% end %>
		</div>
	</div>
<% else %>
You're Not Authorized! Nice Try.
<% end %>

<script>
	var ready = function(){
		$("#codemirror").each(function() {
			CodeMirror.fromTextArea($(this).get(0), {
				lineNumbers: true,
				mode: "<%= @problem.mode %>"
			});
		});
	};
	$(document).ready(ready);
	$(document).on('page:load', ready);
</script>

app/views/problems/get_template.js.erb
$('#codemirror').html('');

app/views/problems/new.html.erb
<% content_for :navbar do %>
	<li> <%= link_to @course.code, @course %> </li>
	<li> <a> > </a> </li>
	<li> <%= link_to @assignment.name, @assignment %> </li>
	<li> <a> > </a> </li>
	<li> <a>New Problem</a> </li>
<% end %>

<div class="page-header">
	<h2>New Problem</h2>
</div>

<% if  current_user && current_user.admin %>
	<div class="panel">
		<div class="panel-body" id="problems_panel">
	    <%= form_for [@assignment, @problem], validate: true do |form| %>
			<!-- Form at the heading -->
	    <div class="row">
	      <div class="form-group col-md-4 col-md-offset-2">
	        <%= form.number_field :number, class: "form-control input-lg", placeholder: "Problem Num." %>
	      </div>
	      <div class="form-group col-md-4">
	        <%= form.number_field :part, class: "form-control input-lg", placeholder: "Part (Optional)" %>
	      </div>
	    </div>
			<!-- Instructions -->
			<div class="col-md-10 col-md-offset-1">
				<h3> <%= form.label :instructions, "Instructions" %> </h3>
	      <%= form.text_area :instructions, id: "instructions", class: "form-control", placeholder: "Instructions Here", style: "width:100%; height:250px;" %>
	    </div>
			<!-- Text area for code -->
	    <div class="col-md-10 col-md-offset-1">
				<br>
				<div class="btn-group">
					<% @templates.each do |t| %>
						<% if !t.removed %>
							<%= link_to t.name, template_fill_form_path(t), remote: true,
							:action => :get, class: "btn btn-style btn-sm"  %>
						<% end %>
					<% end %>
				</div>
				<div class="row">
					<h3 style="display: inline-block;"> <%= form.label :source,  "Template Code" %> </h3>
					<div class="pull-right">
						<br>
						<%= form.select :mode, ::Template::MODES, {}, class: "form-control",
						id: "template_mode", onChange: "changeMode();" %>
					</div>
				</div>
	      <%= form.text_area :source, class: "form control", id: "codemirror", style: "width:100%; height:250px;" %>
			</div>
			<!-- Submit button -->
	    <div class="form-group text-center">
	      <%= form.submit "Create Problem", class: "btn btn-style btn-lg" %>
	    </div>
	    <% end %>
		</div>
	</div>
<% else %>
You're Not Authorized! Nice Try.
<% end %>

<script>
	var codeMirror;
	var temp = function(){
		$('#instructions').val('');
	};
	var changeMode = function(){
		codeMirror.setOption("mode", $('#template_mode').val());
	};
	var ready = function(){
			var current = $('template_mode').val();
			codeMirror = CodeMirror.fromTextArea($('#codemirror')[0], {
				lineNumbers: true,
				mode: current ? current : "<%= ::Template::MODES[0] %>",
				height: "300px"
			});
	};
	$(document).ready(ready);
	$(document).on('page:load', ready);
</script>

app/views/problems/remove.js.erb
$("#problems_panel").html('<%= escape_javascript( render partial: "problems/problem_list", :locals => { assignment: @assignment } ) %>');
$("#flash-container").html('<%= escape_javascript(render :partial => "shared/flash_box") %>');
<% flash.discard %>

app/views/problems/show.html.erb
<% content_for :navbar do %>
	<li> <%= link_to @course.code, @course %> </li>
	<li> <a> > </a> </li>
	<li> <%= link_to @assignment.name, @assignment %> </li>
	<li> <a> > </a> </li>
	<li> <%= link_to get_name, @problem %> </li>
<% end %>

<div class="page-header row">
	<h1 class="pull-left"> <%= get_name %> </h1>
	<%= button_to "Test Cases", problem_test_cases_path(@problem.id),
		class: 'btn btn-lg btn-style pull-right', :method => :get %>
</div>
<h3><%= simple_format @problem.instructions, {}, wrapper_tag: "h4" %></h3>
<%= render :partial => "test_source", :locals => { problem: @problem } %>

<script>
	var ready = function(){
	  $("#codemirror-read").each(function() {
	    CodeMirror.fromTextArea($(this).get(0), {
	      lineNumbers: true,
	      mode: "<%= @problem.mode %>",
	      readOnly: true,
	      scrollbarStyle: "null"
	    });
	  });
	};
	$(document).ready(ready);
	$(document).on('page:load', ready);
</script>