config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root to: "courses#index", :as => :authenticated_root
  end
  unauthenticated do
    root to: redirect("/users/sign_in")
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations", :confirmations => "confirmations",
    :passwords => "passwords" }
  get '/privacy', to: 'application#privacy'
  resources :templates do
    get 'remove'
    get 'fill_form'
  end

  resources :courses do
    get 'remove'
    resources :assignments, shallow: true do
      get 'remove'
      resources :problems, shallow: true do
        get 'remove'
        resources :test_cases, shallow: true do
          get 'toggle_flag'
          get 'remove'
          get 'edit'
          get 'cancel'
        end
      end
    end
  end

end

app/views/shared/_flash_box.html.erb
<div id="flash-container">
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% elsif alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default nav-style">
  <div class="container-fluid">
    <!-- For Mobile + Brand -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapseNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand-style navbar-brand" href="/">Muriqui</a>
    </div>

    <!-- Only shown if logged in -->
    <div class="collapse navbar-collapse" id="collapseNavbar">
      <% if current_user %>
        <ul class="nav navbar-nav">
          <%= yield :navbar %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <!-- If not from Facebook -->
          <% if !current_user.uid %>
            <li>
              <%= button_to "Change Password", edit_user_registration_path, :method => :get,
              class: 'btn pull-right btn-default navbar-btn nav-btn-style' %>
            </li>
          <% end %>
          <!-- Admin -->
          <% if current_user.admin %>
            <li>
              <%= button_to "Templates", templates_path, :method => :get,
              class: 'btn pull-right btn-default navbar-btn nav-btn-style' %>
            </li>
          <% end %>
          <!-- Logout Button -->
          <li>
            <%= button_to "Logout", "/users/sign_out", :method => :delete,
            class: 'btn pull-right btn-default navbar-btn nav-btn-style' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>